//! Context Package — the AI-ready context bundle.
//!
//! Context Packages are generated by the Context Engine and contain
//! only the relevant knowledge for a specific request. AI never
//! receives raw databases or entire repositories.

use serde::{Deserialize, Serialize};

use crate::domain::node::Node;
use crate::domain::relationship::Relationship;
use crate::domain::rule::Rule;

/// A compressed, AI-ready context package.
///
/// Generated by the Context Engine pipeline:
/// Intent Detection → Node Discovery → Dependency Expansion →
/// Decision Retrieval → Rule Retrieval → Risk Analysis →
/// Context Compression → Context Package
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContextPackage {
    /// The original request/query this context was generated for.
    pub query: String,

    /// Relevant nodes discovered and expanded.
    pub nodes: Vec<Node>,

    /// Relevant relationships between the included nodes.
    pub relationships: Vec<Relationship>,

    /// Active rules that apply to the context.
    pub rules: Vec<Rule>,

    /// Architecture decisions relevant to the context.
    pub decisions: Vec<Node>,

    /// Known risks related to the context.
    pub risks: Vec<String>,

    /// Roadmap items affected by or related to the context.
    pub roadmap_items: Vec<Node>,

    /// Relevant file paths.
    pub files: Vec<String>,

    /// Relevant API endpoints.
    pub apis: Vec<String>,

    /// Relevant database tables.
    pub database_tables: Vec<String>,
}

impl ContextPackage {
    /// Create an empty context package for the given query.
    pub fn empty(query: impl Into<String>) -> Self {
        Self {
            query: query.into(),
            nodes: Vec::new(),
            relationships: Vec::new(),
            rules: Vec::new(),
            decisions: Vec::new(),
            risks: Vec::new(),
            roadmap_items: Vec::new(),
            files: Vec::new(),
            apis: Vec::new(),
            database_tables: Vec::new(),
        }
    }

    /// Return the total number of items in this context package.
    pub fn total_items(&self) -> usize {
        self.nodes.len()
            + self.relationships.len()
            + self.rules.len()
            + self.decisions.len()
            + self.risks.len()
            + self.roadmap_items.len()
            + self.files.len()
            + self.apis.len()
            + self.database_tables.len()
    }

    /// Whether this context package is empty.
    pub fn is_empty(&self) -> bool {
        self.total_items() == 0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_context_package() {
        let pkg = ContextPackage::empty("Add cashback feature");
        assert_eq!(pkg.query, "Add cashback feature");
        assert!(pkg.is_empty());
        assert_eq!(pkg.total_items(), 0);
    }

    #[test]
    fn context_package_serde_roundtrip() {
        let pkg = ContextPackage::empty("Test query");
        let json = serde_json::to_string(&pkg).unwrap();
        let deserialized: ContextPackage = serde_json::from_str(&json).unwrap();
        assert_eq!(pkg.query, deserialized.query);
        assert!(deserialized.is_empty());
    }
}
