use chrono::{DateTime, Utc};
use sentinel_arc_core::{EventId, EventType};
use serde::{Deserialize, Serialize};

/// Represents the scope of the generated timeline.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TimelineType {
    /// A timeline for a specific feature node.
    Feature,
    /// A global timeline of all architectural decisions.
    Decision,
    /// A timeline for a specific roadmap item.
    Roadmap,
    /// A global timeline encompassing the entire project.
    Project,
}

/// A human-readable presentation of an underlying Event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TimelineEvent {
    pub event_id: EventId,
    pub timestamp: DateTime<Utc>,
    pub author: String,
    pub event_type: EventType,
    /// A human-readable description generated by the TimelineEngine based on the event payload.
    pub description: String,
}

/// A collection of chronological events representing history.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Timeline {
    pub entity_id: Option<String>,
    pub timeline_type: TimelineType,
    pub events: Vec<TimelineEvent>,
    pub generated_at: DateTime<Utc>,
}

impl Timeline {
    pub fn new(
        entity_id: Option<String>,
        timeline_type: TimelineType,
        events: Vec<TimelineEvent>,
    ) -> Self {
        Self {
            entity_id,
            timeline_type,
            events,
            generated_at: Utc::now(),
        }
    }
}
