//! Knowledge source types and confidence scoring.
//!
//! Derived from DOMAIN_MODEL.md. The confidence system determines how
//! trustworthy a piece of knowledge is based on its origin.

use serde::{Deserialize, Serialize};
use std::fmt;

/// The origin of a piece of knowledge.
///
/// Higher-priority sources override lower-priority sources when conflicts
/// are detected (Knowledge Drift).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Source {
    /// Extracted directly from source code. Highest trust.
    Code,
    /// Derived from Git history (commits, blame, etc.).
    Git,
    /// Entered manually by a user.
    Manual,
    /// Extracted from documentation files.
    Documentation,
    /// Generated by an AI system. Lowest trust.
    Ai,
    /// Imported from an external system.
    Imported,
}

impl Source {
    /// Return the default confidence score for this source type.
    ///
    /// These values are defined in the Domain Model:
    /// - Code = 100
    /// - Git = 95
    /// - Decision = 90 (handled separately via node type)
    /// - Documentation = 60
    /// - Manual = 40
    /// - AI = 20
    pub fn default_confidence(&self) -> Confidence {
        match self {
            Self::Code => Confidence::new(100),
            Self::Git => Confidence::new(95),
            Self::Manual => Confidence::new(40),
            Self::Documentation => Confidence::new(60),
            Self::Ai => Confidence::new(20),
            Self::Imported => Confidence::new(50),
        }
    }

    /// Return the priority rank (1 = highest, 7 = lowest).
    ///
    /// From the Domain Model source priority order.
    pub fn priority(&self) -> u8 {
        match self {
            Self::Code => 1,
            Self::Git => 2,
            // Rules/Decisions priority (3/4) are handled by node type, not source.
            Self::Documentation => 5,
            Self::Manual => 6,
            Self::Ai => 7,
            Self::Imported => 6, // Same priority as Manual
        }
    }

    /// Return all known source types.
    pub fn all() -> &'static [Source] {
        &[
            Self::Code,
            Self::Git,
            Self::Manual,
            Self::Documentation,
            Self::Ai,
            Self::Imported,
        ]
    }
}

impl fmt::Display for Source {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Code => write!(f, "Code"),
            Self::Git => write!(f, "Git"),
            Self::Manual => write!(f, "Manual"),
            Self::Documentation => write!(f, "Documentation"),
            Self::Ai => write!(f, "AI"),
            Self::Imported => write!(f, "Imported"),
        }
    }
}

/// A confidence score from 0 to 100 indicating how trustworthy a piece
/// of knowledge is.
///
/// - 100: Highest confidence (directly from source code)
/// - 0: No confidence
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Confidence(u8);

impl Confidence {
    /// Create a new confidence value, clamped to [0, 100].
    pub fn new(value: u8) -> Self {
        Self(value.min(100))
    }

    /// Return the underlying numeric value.
    pub fn value(&self) -> u8 {
        self.0
    }

    /// Whether this confidence level is considered high (>= 80).
    pub fn is_high(&self) -> bool {
        self.0 >= 80
    }

    /// Whether this confidence level is considered low (< 40).
    pub fn is_low(&self) -> bool {
        self.0 < 40
    }
}

impl Default for Confidence {
    fn default() -> Self {
        Self(50)
    }
}

impl fmt::Display for Confidence {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}%", self.0)
    }
}

impl From<u8> for Confidence {
    fn from(v: u8) -> Self {
        Self::new(v)
    }
}

impl From<Confidence> for u8 {
    fn from(c: Confidence) -> u8 {
        c.0
    }
}

impl From<Confidence> for i64 {
    fn from(c: Confidence) -> i64 {
        c.0 as i64
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn confidence_clamped_to_100() {
        let c = Confidence::new(200);
        assert_eq!(c.value(), 100);
    }

    #[test]
    fn confidence_ordering() {
        let low = Confidence::new(20);
        let high = Confidence::new(80);
        assert!(high > low);
    }

    #[test]
    fn source_priority_ordering() {
        assert!(Source::Code.priority() < Source::Git.priority());
        assert!(Source::Git.priority() < Source::Documentation.priority());
        assert!(Source::Documentation.priority() < Source::Ai.priority());
    }

    #[test]
    fn source_default_confidences() {
        assert_eq!(Source::Code.default_confidence().value(), 100);
        assert_eq!(Source::Git.default_confidence().value(), 95);
        assert_eq!(Source::Documentation.default_confidence().value(), 60);
        assert_eq!(Source::Manual.default_confidence().value(), 40);
        assert_eq!(Source::Ai.default_confidence().value(), 20);
    }

    #[test]
    fn confidence_classification() {
        assert!(Confidence::new(100).is_high());
        assert!(Confidence::new(80).is_high());
        assert!(!Confidence::new(79).is_high());
        assert!(Confidence::new(20).is_low());
        assert!(Confidence::new(0).is_low());
        assert!(!Confidence::new(40).is_low());
    }

    #[test]
    fn source_serde_roundtrip() {
        for src in Source::all() {
            let json = serde_json::to_string(src).unwrap();
            let deserialized: Source = serde_json::from_str(&json).unwrap();
            assert_eq!(*src, deserialized);
        }
    }

    #[test]
    fn confidence_serde_roundtrip() {
        let c = Confidence::new(75);
        let json = serde_json::to_string(&c).unwrap();
        assert_eq!(json, "75");
        let deserialized: Confidence = serde_json::from_str(&json).unwrap();
        assert_eq!(c, deserialized);
    }
}
